# Generated by Django 3.0.6 on 2020-10-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
