# Generated by Django 3.0.6 on 2020-10-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
                ('soft', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TakeOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('where', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
