# Generated by Django 3.0.6 on 2020-10-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_soft_takeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saying', models.CharField(max_length=300)),
            ],
        ),
    ]
