# Generated by Django 3.0.6 on 2020-10-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_saying'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saying', models.CharField(max_length=400)),
                ('url', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=6)),
                ('date', models.CharField(max_length=8)),
            ],
        ),
    ]
